openapi: "3.0.3"
servers:
  - url: 'https://api.affinda.com/v1'
info:
  description: >-
    Documentation for the [Affinda API](https://github.com/affinda/affinda-api-spec).

    # Quickstart

    * Obtain an [API key](https://affinda.com/resume-parser/free-api-key/)

    * (Recommended) Download and install one of our client libraries:
      * [Python](https://github.com/affinda/affinda-python) : `pip install affinda`
      * [Javascript](https://github.com/affinda/affinda-python) : `npm install @affinda/affinda`
      * [C# - coming soon](https://github.com/affinda/affinda-csharp)
      * [Java - coming soon](https://github.com/affinda/affinda-java)

    * Without a client library, API requests via HTTP can be made as defined below

  version: v1
  title: Affinda API
  contact:
    email: contact@affinda.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/affinda/affinda-api-spec/main/LICENSE'
  x-logo:
    url: 'https://api.affinda.com/static/documentation/affinda_logo_black.png'
    backgroundColor: '#FFFFFF'
    altText: Affinda logo
tags:
  - name: Parser
    description: Operations available to perform on parsed resumes
  - name: Redactor
    description: Operations available to perform on redacted resumes
  - name: Reformatter
    description: Operations available to perform on reformatted resumes
x-tagGroups:
  - name: Resumes
    tags:
      - Parser
      - Redactor
      - Reformatter
security:
  - ApiKeyAuth: [ ]
paths:
  /resumes:
    $ref: 'paths/resumes.yaml'
  '/resumes/{identifier}':
    $ref: 'paths/resumes@{identifier}.yaml'
  /redacted_resumes:
    $ref: 'paths/redacted_resumes.yaml'
  '/redacted_resumes/{identifier}':
    $ref: 'paths/redacted_resumes@{identifier}.yaml'
  /resume_formats:
    $ref: 'paths/resume_formats.yaml'
  /reformatted_resumes:
    $ref: 'paths/reformatted_resumes.yaml'
  '/reformatted_resumes/{identifier}':
    $ref: 'paths/reformatted_resumes@{identifier}.yaml'
components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      description: >-
        Basic authentication using an API key, e.g. `{Authorization: Bearer
        75z0bb4fbdf97b7e4111ff6c0015471094155f91}`

        You can obtain an API key [here](https://affinda.com/resume-parser/free-api-key/)
